# Generated by Django 4.0 on 2022-01-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authez', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='authez.Profile'),
        ),
    ]
